openapi: 3.0.0
info:
  title: マッチングアプリBE API
  version: 0.0.1
servers:
  - url: http://dateApp.com
paths:
  /human/list:
    get:
      summary: マッチング済みの相手の情報を一覧で取得
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    tag:
                      type: string
